name: Main

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo lol > Release.txt
      - name: Test
        run: cat Release.txt
      - name: some python things
        run: |
          pip --version
      - name: Display Python versionBefore
        run: python -c "import sys; print(sys.version)"
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
        # You can test your matrix by printing the current Python version
      - name: Display Python versionAFter
        run: python -c "import sys; print(sys.version)"
      - name: some python things after
        run: |
          pip --version
          pip install  PyQt5 pyqt5-tools
          Set-Alias -Name lrelease  -value C:\hostedtoolcache\windows\Python\3.9.13\x86\lib\site-packages\qt5_applications\Qt\bin\lrelease.exe
          lrelease -version
          
      #- name: Release
       # uses: softprops/action-gh-release@v1
        #with:
         # tag_name: v1222
          #files: Release.txt
