name: Main

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo lol > Release.txt
      - name: Test
        run: cat Release.txt
      - name: some python things
        run: |
          conda --version
          pip --version

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1222
          files: Release.txt
